[package]
name = "alloy"
version = "0.1.0"
edition = "2021"
authors = ["@ovnanova"]
description = "Alloy"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/ovnanova/alloy"

[dependencies]
# No external dependencies!

[[bin]]
name = "alloy"
path = "src/main.rs"
